//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkOfGroceryStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int ID_cheque { get; set; }
        public int ID_order { get; set; }
        public int ID_reserve { get; set; }
        public int ID_customers { get; set; }
        public int ID_sale { get; set; }
        public int Amount { get; set; }
        public System.DateTime OrderData { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Reserve Reserve { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
