//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkOfGroceryStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Reserve_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Reserve_Invoice()
        {
            this.Reserve = new HashSet<Reserve>();
        }
    
        public int ID_sal_res_inv { get; set; }
        public int ID_invoice_products { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> PriceUnit { get; set; }
        public int ID_SalersInvoice { get; set; }
    
        public virtual Invoice_Products Invoice_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserve> Reserve { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
