//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkOfGroceryStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int ID_timetable { get; set; }
        public int ID_workers { get; set; }
        public int ID_store { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<double> Salary { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
