//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkOfGroceryStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCheque
    {
        public string Name { get; set; }
        public string Firm { get; set; }
        public string BarCode { get; set; }
        public Nullable<double> Price { get; set; }
        public int Amount { get; set; }
        public double TotalSum { get; set; }
        public Nullable<int> Percents { get; set; }
        public string Surname { get; set; }
        public string NameCustomer { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> Discount { get; set; }
        public string SurnameWorkers { get; set; }
        public string NameWorkers { get; set; }
        public System.DateTime OrderData { get; set; }
        public string Address { get; set; }
    }
}
