//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkOfGroceryStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductOfSubtypes
    {
        public string Назва_продукту { get; set; }
        public string Виробник { get; set; }
        public Nullable<double> Ціна { get; set; }
        public Nullable<int> Кількість { get; set; }
        public Nullable<double> Розмір { get; set; }
        public int ID_product { get; set; }
        public string Група { get; set; }
    }
}
